services:
  frontend:
    build:
      context: ../
      dockerfile: frontend/Dockerfile
      target: development
    volumes:
      # Creating this volume will make Docker update changes from local automatically
      - ./:/usr/src/app
      # Mark these as volumes so they get ignored
      - /usr/src/app/node_modules
      - /usr/src/app/.svelte-kit
      - /usr/src/app/.vite
      - /usr/src/app/android
      - /usr/src/app/ios
    ports:
      - '${FRONTEND_PORT}:${FRONTEND_PORT}'
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://127.0.0.1:${FRONTEND_PORT}/ || exit 1
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 15s
    restart: on-failure
