services:
  frontend:
    build:
      context: ../
      dockerfile: frontend/Dockerfile
      target: development
    volumes:
      # Creating this volume will make Docker update changes from local automatically
      - ./:/opt/frontend
      # Local data
      - ./data:/var/data/local
      # Cache volume
      - cache:/var/data/cache
      # Mark these as volumes so they get ignored
      - /opt/frontend/node_modules
      - /opt/frontend/.svelte-kit
      - /opt/frontend/.vite
      - /opt/frontend/android
      - /opt/frontend/ios
    ports:
      - '${FRONTEND_PORT}:${FRONTEND_PORT}'
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://127.0.0.1:${FRONTEND_PORT}/ || exit 1
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 15s
    restart: on-failure
