services:
  frontend:
    build:
      context: ../
      dockerfile: frontend/Dockerfile
      target: production
    ports:
      - '80:3000'
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://127.0.0.1:3000/ || exit 1
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 15s
    restart: always
