version: "3.4"

services:
  frontend:
    extends:
      file: ./frontend/docker-compose.dev.yml
      service: frontend
    depends_on:
      - "strapi"
    environment:
      - VITE_BACKEND_URL=${VITE_BACKEND_URL}
      - VITE_PUBLIC_BACKEND_URL=${VITE_PUBLIC_BACKEND_URL}
      - VITE_STRAPI_TOKEN=${VITE_STRAPI_TOKEN}
  strapi:
    extends:
      file: ./backend/vaa-strapi/docker-compose.dev.yml
      service: strapi
    environment:
      HOST: ${HOST}
      PORT: ${PORT}
      APP_KEYS: ${APP_KEYS}
      API_TOKEN_SALT: ${API_TOKEN_SALT}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      JWT_SECRET: ${JWT_SECRET}
      DATABASE_HOST: postgres
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_SCHEMA: ${DATABASE_SCHEMA}
      DATABASE_SSL_SELF: ${DATABASE_SSL_SELF}
      GENERATE_MOCK_DATA_ON_INITIALISE: ${GENERATE_MOCK_DATA_ON_INITIALISE}
      GENERATE_MOCK_DATA_ON_RESTART: ${GENERATE_MOCK_DATA_ON_RESTART}
  postgres:
    extends:
      file: ./backend/vaa-strapi/docker-compose.dev.yml
      service: postgres
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
