source .env
echo POSTGRES_PASSWORD=$DATABASE_PASSWORD
echo POSTGRES_USER=$DATABASE_USERNAME
echo POSTGRES_DB=$DATABASE_NAME
docker run --name vaa-database -e POSTGRES_PASSWORD=$DATABASE_PASSWORD -e POSTGRES_USER=$DATABASE_USERNAME -e POSTGRES_DB=$DATABASE_NAME -p 5432:5432 -d postgres
