import * as m from '$lib/paraglide/messages';
import { logDebugError } from '$lib/utils/logger';
import { getOverride } from './overrides';
import type { TranslationKey } from '$lib/types/generated/translationKey';

type MessageModule = Record<string, (params?: Record<string, unknown>) => string>;

/**
 * Translation wrapper: checks runtime overrides first, then falls back to Paraglide.
 *
 * Usage: t('dynamic.appName') or t('results.candidate.numShown', { numShown: count })
 *
 * The `key` parameter is typed against the auto-generated `TranslationKey` union
 * (see `apps/frontend/src/lib/types/generated/translationKey.ts`, generated by
 * `apps/frontend/tools/translationKey/generateTranslationKeyType.ts`). This gives
 * callers compile-time validation that the key exists in the message catalog.
 *
 * @param key - Dot-notation translation key, must be a `TranslationKey` union member
 * @param params - Optional parameters for interpolation
 * @returns Translated string
 */
export function t(key: TranslationKey, params?: Record<string, unknown>): string {
  // 1. Check runtime overrides (from backend translationOverrides)
  const override = getOverride(key, params);
  if (override !== undefined) return override;

  // 2. Fall back to Paraglide compiled message
  const messageFn = (m as unknown as MessageModule)[key];
  if (typeof messageFn === 'function') {
    try {
      return messageFn(params);
    } catch (e) {
      logDebugError(e);
      return key;
    }
  }

  // 3. Key not found -- return key as fallback
  return key;
}
