import { Argument } from '../base/argument';
import { PromptCall } from '../llm/promptCall';

/**
 * Result from a single condensation step (map, reduce, iterateMap or refine)
 */
export interface CondensationStepResult {
  /** The arguments generated by the step */
  arguments: Array<Argument> | Array<Array<Argument>>;
  /** The prompt calls made by the step */
  promptCalls: Array<PromptCall>;
  /** The node IDs of the arguments */
  nodeIds?: Array<string>;
  /** How many step levels this operation consumed (default 1) */
  stepLevelsConsumed?: number; 
}
