version: '3.1'

services:
  strapi:
    build:
      context: .
      target: development
    ports:
      - 1337:1337
    restart: always
    environment:
      HOST: ${HOST}
      PORT: ${PORT}
      APP_KEYS: ${APP_KEYS}
      API_TOKEN_SALT: ${API_TOKEN_SALT}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      JWT_SECRET: ${JWT_SECRET}
      DATABASE_HOST: postgres
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_SCHEMA: ${DATABASE_SCHEMA}
      DATABASE_SSL_SELF: ${DATABASE_SSL_SELF}
      GENERATE_MOCK_DATA_ON_INITIALISE: ${GENERATE_MOCK_DATA_ON_INITIALISE}
      GENERATE_MOCK_DATA_ON_RESTART: ${GENERATE_MOCK_DATA_ON_RESTART}
    depends_on:
      - 'postgres'
    volumes:
      # Creating this volume will make Docker update changes from local automatically
      # Uncomment if you want to enable mounting Strapi to disk / hot reloading
      # Uncommenting is required if you update content model and want to sync changes to Git
      #- ./:/opt
      # Mark these as volumes so they get ignored
      - /opt/node_modules
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: always

  adminer:
    image: adminer
    restart: always
    ports:
      - 4567:8080
