version: '3.1'

services:
  strapi:
    build:
      # Context includes the root of the repository so that we can expose shared/ module.
      context: ../../
      dockerfile: backend/vaa-strapi/Dockerfile
      target: production
    ports:
      - '1337:1337'
    restart: always
    environment:
      HOST: ${HOST}
      PORT: ${PORT}
      APP_KEYS: ${APP_KEYS}
      API_TOKEN_SALT: ${API_TOKEN_SALT}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      JWT_SECRET: ${JWT_SECRET}
      DATABASE_HOST: postgres
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_SCHEMA: ${DATABASE_SCHEMA}
      DATABASE_SSL_SELF: ${DATABASE_SSL_SELF}
      GENERATE_MOCK_DATA_ON_INITIALISE: ${GENERATE_MOCK_DATA_ON_INITIALISE}
    depends_on:
      - 'postgres'
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:1337/ || exit 1
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 45s
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
      - strapi-uploads:/opt/public/uploads
    ports:
      - '5432:5432'
    restart: always

  adminer:
    image: adminer
    restart: always
    ports:
      - '4567:8080'

volumes:
  postgres:
  strapi-uploads:
