/**
 * `buildMinimal` — fresh-minimal Template authoring helper for the perm family (and minimal-topology perms generally).
 *
 * Authors a fresh `Template` object from the existing `e2e/perm/shared.ts` building blocks. The helper is a thin compositional layer — it does NOT introduce new row shapes or new external_id conventions. Every row it emits flows through the same writer that consumes hand-authored perm templates.
 *
 * Default shape:
 *   - 1 election (`el-1`)
 *   - 1 constituency group (`cg-1`)
 *   - 1 constituency (`co-1a`)
 *   - 2 organisations (`or-1` / `or-2`) — pass `organizations: 1` to truncate to a single org (perm-localisation-positive shape)
 *   - 1 candidate (`cand-1`)
 *   - 1 opinion (Likert-5) question (`qu-opin-l5-1`)
 *   - 0 info questions
 *   - 1 nomination per (election × constituency × candidate)
 *   - app_settings = MINIMAL_BASE_APP_SETTINGS (deep-merged with `settingsOverlay` when provided)
 *
 * The default answer-fill behaviour is answers-filled: every candidate generated by buildMinimal carries an answer to every seeded question.
 * Override per-candidate via `answersByCandidate[<id>] = 'none'` for a clean candidate, OR an explicit map for specific overrides. Global override via `candidateAnswersDefault: 'none'`.
 *
 * Per-perm `externalIdPrefix` invariant is preserved: the value passed via {@link BuildMinimalOptions.externalIdPrefix} is the EXACT `template.externalIdPrefix` returned (no mutation, no normalisation).
 * The writer prepends this prefix to every bare external_id at write time (`setupFromTemplate.ts:131-137`).
 *
 * JSONB-undefined safety: the deep-merge utility strips `undefined` values before merging. JSONB drops `undefined` keys at write time and the post-seed `toMatchObject` assertion in `setupFromTemplate` fails if an undefined key leaks into the merged settings tree.
 */

import {
  buildCandidate,
  buildElectionConstituencyNoms,
  buildOrganizations,
  buildQuestionCategories,
  LIKERT_5_EN,
  MINIMAL_BASE_APP_SETTINGS
} from '../e2e/perm/shared';
import type { Json } from '@openvaa/supabase-types';
import type {
  CandidatesFixedRow,
  ConstituenciesFixedRow,
  ConstituencyGroupsFixedRow,
  ElectionsFixedRow,
  NominationsFixedRow,
  QuestionsFixedRow
} from '../../template/permittedKeys';
import type { Template } from '../../template/types';

/**
 * Per-question answer payload — keyed by FULL prefixed question external_id.
 *
 * Re-uses the same shape as `BuildCandidateOptions.answersByExternalId`.
 */
type AnswerEntry = { value: unknown; info?: { en: string } };

/**
 * Per-candidate answer-override directive.
 *
 *   - `'none'` → empty answer map (clean candidate, ignore the default).
 *   - `Record<string, AnswerEntry>` → explicit map (overrides the default
 *     fill); the helper does NOT merge with the default — the explicit map is the entire answer set for the candidate.
 *
 * Keys are BARE question external_ids (e.g. `'qu-opin-l5-1'`); the helper normalises them to FULL prefixed external_ids before passing to `buildCandidate`.
 */
type CandidateAnswerOverride = 'none' | Record<string, AnswerEntry>;

/**
 * Options accepted by {@link buildMinimal}. All fields named — no positional API (named-params convention).
 */
export interface BuildMinimalOptions {
  /** Required: unique per-perm external_id prefix (e.g. `'e2e-perm-answers-locked-'`). */
  externalIdPrefix: string;
  /** Number of candidates. Default: 1. */
  candidates?: number;
  /** Number of opinion questions (Likert-5 singleChoiceOrdinal). Default: 1. */
  opinionQuestions?: number;
  /** Number of info questions (text). Default: 0. */
  infoQuestions?: number;
  /** Number of elections. Default: 1. All elections share the single CG/CO. */
  elections?: number;
  /** Number of organisations. Default: 2. Pass 1 for single-org perms. */
  organizations?: 1 | 2;
  /**
   * Per-question custom_data overrides. Keyed by BARE question external_id (e.g. `'qu-opin-l5-1'`).
   */
  customDataByQuestion?: Record<string, Json>;
  /**
   * Per-candidate answer overrides. Keyed by BARE candidate external_id (e.g. `'cand-1'`).
   */
  answersByCandidate?: Record<string, CandidateAnswerOverride>;
  /** Settings overlay applied via deep-merge onto MINIMAL_BASE_APP_SETTINGS. */
  settingsOverlay?: Record<string, unknown>;
  /**
   * When `elections > 1`, controls which elections receive nominations.
   * Default: all elections receive nominations. Pass `[0]` to give nominations only to el-1 (perm-missing-nominations shape).
   */
  nominationsInElectionIndices?: Array<number>;
  /**
   * Global default answer-fill behaviour. `'all'` (default) — every candidate carries an answer to every seeded question. `'none'` — every candidate is clean. Per-candidate `answersByCandidate[<id>]` still overrides this global default.
   */
  candidateAnswersDefault?: 'all' | 'none';
}

/**
 * JSONB-safe deep merge. Recursively merges `overlay` into `base`. Strips `undefined` values from the overlay before each merge step.
 *
 * Returns a fresh object — does not mutate either argument.
 */
function deepMerge<TRow extends Record<string, unknown>>(
  base: TRow,
  overlay: Record<string, unknown> | undefined
): TRow {
  if (overlay == null) return JSON.parse(JSON.stringify(base)) as TRow;
  const out: Record<string, unknown> = JSON.parse(JSON.stringify(base));
  for (const key of Object.keys(overlay)) {
    const overlayVal = overlay[key];
    if (overlayVal === undefined) continue; // Strip undefined for JSONB safety.
    const baseVal = out[key];
    const overlayIsPlainObj = overlayVal != null && typeof overlayVal === 'object' && !Array.isArray(overlayVal);
    const baseIsPlainObj = baseVal != null && typeof baseVal === 'object' && !Array.isArray(baseVal);
    if (overlayIsPlainObj && baseIsPlainObj) {
      out[key] = deepMerge(baseVal as Record<string, unknown>, overlayVal as Record<string, unknown>);
    } else {
      out[key] = overlayVal;
    }
  }
  return out as TRow;
}

/**
 * Build the default answer entry for a question of the given shape:
 *   - info (`text`) → `{ value: { en: '[<extId>] desc' } }`
 *   - opinion (`singleChoiceOrdinal` / Likert5) → `{ value: choices[middle].id }` (median; Likert-5 resolves to `'3'`)
 *   - opinion (`boolean`) → `{ value: true }`
 *   - opinion categorical → `{ value: <first-category-id> }`
 */
export function defaultAnswerForQuestion(question: Record<string, unknown>, fullExtId: string): AnswerEntry {
  const type = question.type as string;
  if (type === 'text') {
    return { value: { en: `[${fullExtId}] desc` } };
  }
  if (type === 'singleChoiceOrdinal') {
    // Pick the median (middle) ordinal choice so the default lands on the neutral option regardless of the scale length; Likert-5 resolves to id '3'.
    const choices = question.choices as Array<{ id: string }> | undefined;
    if (Array.isArray(choices) && choices.length > 0) {
      return { value: choices[Math.floor((choices.length - 1) / 2)].id };
    }
    return { value: '3' };
  }
  if (type === 'boolean') {
    return { value: true };
  }
  if (type === 'number') {
    // the backend validate_answer_value 'number' branch requires a JSON number. Return the midpoint of the question's min/max (read from custom_data, falling back to top-level min/max), else 0. Never a string.
    const cd = (question.custom_data ?? {}) as Record<string, unknown>;
    const min =
      typeof cd.min === 'number' ? cd.min : typeof question.min === 'number' ? (question.min as number) : undefined;
    const max =
      typeof cd.max === 'number' ? cd.max : typeof question.max === 'number' ? (question.max as number) : undefined;
    if (min !== undefined && max !== undefined) {
      return { value: Math.round((min + max) / 2) };
    }
    return { value: 0 };
  }
  if (type === 'multipleChoiceCategorical') {
    // the validate_answer_value 'multipleChoiceCategorical' branch requires an array of valid choice ids — a scalar choice id is invalid. Return the first max(minSelections ?? 1, 1) choice ids.
    const mcChoices = question.choices as Array<{ id: string }> | undefined;
    if (Array.isArray(mcChoices) && mcChoices.length > 0) {
      const cd = (question.custom_data ?? {}) as Record<string, unknown>;
      const minSel = typeof cd.minSelections === 'number' ? cd.minSelections : 1;
      const take = Math.min(Math.max(minSel, 1), mcChoices.length);
      return { value: mcChoices.slice(0, take).map((c) => c.id) };
    }
    return { value: [] };
  }
  // Categorical (or any other choice-based question): pick the first choice's id when available; otherwise fall back to empty string.
  const choices = question.choices as Array<{ id: string }> | undefined;
  if (Array.isArray(choices) && choices.length > 0) {
    return { value: choices[0].id };
  }
  return { value: '' };
}

/**
 * Compose a fresh-minimal Template from the named options. See module doc-comment for the default shape + override surface.
 */
export function buildMinimal(opts: BuildMinimalOptions): Template {
  const {
    externalIdPrefix: P,
    candidates: candCount = 1,
    opinionQuestions: opinCount = 1,
    infoQuestions: infoCount = 0,
    elections: electionCount = 1,
    organizations: orgCount = 2,
    customDataByQuestion = {},
    answersByCandidate = {},
    settingsOverlay,
    nominationsInElectionIndices,
    candidateAnswersDefault = 'all'
  } = opts;

  // --- Elections ----------------------------------------------------------
  const elections: Array<ElectionsFixedRow> = [];
  for (let i = 0; i < electionCount; i++) {
    const idx = i + 1;
    elections.push({
      external_id: `el-${idx}`,
      name: { en: `[EL${idx}] Election ${idx}` },
      short_name: { en: `EL${idx}` },
      election_type: idx === 1 ? 'general' : 'local',
      election_date: '2026-06-15',
      sort_order: i,
      is_generated: false,
      multiple_rounds: false,
      current_round: 1,
      constituency_groups: [{ external_id: `${P}cg-1` }]
    });
  }

  // --- Constituency group + constituency ---------------------------------
  const constituency_groups: Array<ConstituencyGroupsFixedRow> = [
    {
      external_id: 'cg-1',
      name: { en: '[CG1] Only group' },
      sort_order: 0,
      is_generated: false,
      constituencies: [{ external_id: `${P}co-1a` }]
    }
  ];
  const constituencies: Array<ConstituenciesFixedRow> = [
    {
      external_id: 'co-1a',
      name: { en: '[CO1A] Only constituency' },
      sort_order: 0,
      is_generated: false
    }
  ];

  // --- Organisations -----------------------------------------------------
  const allOrgs = buildOrganizations();
  const orgs = orgCount === 1 ? allOrgs.slice(0, 1) : allOrgs;

  // --- Question categories -----------------------------------------------
  const question_categories = buildQuestionCategories();

  // --- Questions --------------------------------------------------------- Build the M+K = opinionQuestions + infoQuestions question list. Each question's external_id is BARE; the writer prepends `P`. customData overlays are matched by BARE external_id.
  const questions: Array<QuestionsFixedRow> = [];
  for (let i = 0; i < opinCount; i++) {
    const idx = i + 1;
    const extId = `qu-opin-l5-${idx}`;
    const q: QuestionsFixedRow = {
      external_id: extId,
      type: 'singleChoiceOrdinal',
      name: { en: `[QU-OPIN-L5-${idx}] [${P}${extId}] desc` },
      choices: LIKERT_5_EN,
      category: { external_id: `${P}qc-opin` },
      allow_open: false,
      required: idx === 1,
      sort_order: 100 + i,
      is_generated: false
    };
    if (customDataByQuestion[extId] !== undefined) {
      q.custom_data = customDataByQuestion[extId];
    }
    questions.push(q);
  }
  for (let i = 0; i < infoCount; i++) {
    const idx = i + 1;
    const extId = `qu-info-${idx}`;
    const q: QuestionsFixedRow = {
      external_id: extId,
      type: 'text',
      name: { en: `[QU-INFO-${idx}] [${P}${extId}] desc` },
      category: { external_id: `${P}qc-info` },
      allow_open: false,
      required: false,
      sort_order: i,
      is_generated: false
    };
    if (customDataByQuestion[extId] !== undefined) {
      q.custom_data = customDataByQuestion[extId];
    }
    questions.push(q);
  }

  // --- Candidates -------------------------------------------------------- Compute the per-candidate answer map then call buildCandidate.
  const candidatesArr: Array<CandidatesFixedRow> = [];
  for (let i = 0; i < candCount; i++) {
    const candIdx = i + 1;
    const bareCandId = `cand-${candIdx}`;
    const orgN: 1 | 2 = orgCount === 1 ? 1 : i % 2 === 0 ? 1 : 2;
    const letter = String.fromCharCode('A'.charCodeAt(0) + i);

    // Resolve the answer map for this candidate.
    const override = answersByCandidate[bareCandId];
    let answersMap: Record<string, AnswerEntry>;
    if (override === 'none') {
      answersMap = {};
    } else if (override && typeof override === 'object') {
      // Explicit map — normalise BARE → FULL prefixed keys.
      answersMap = {};
      for (const [bareQId, entry] of Object.entries(override)) {
        answersMap[`${P}${bareQId}`] = entry;
      }
    } else if (candidateAnswersDefault === 'none') {
      answersMap = {};
    } else {
      // candidateAnswersDefault === 'all' — fill every seeded question.
      answersMap = {};
      for (const q of questions) {
        const bareId = q.external_id as string;
        const fullId = `${P}${bareId}`;
        answersMap[fullId] = defaultAnswerForQuestion(q, fullId);
      }
    }

    candidatesArr.push(
      buildCandidate({
        prefix: P,
        orgN,
        candLetter: letter,
        idSuffix: bareCandId,
        sortOrder: i,
        answersByExternalId: answersMap
      })
    );
  }

  // --- Nominations -------------------------------------------------------
  const candIdSuffixes = candidatesArr.map((c) => c.external_id as string);
  const allElectionIndices: Array<number> = [];
  for (let i = 0; i < electionCount; i++) allElectionIndices.push(i);
  const electionsWithNoms = nominationsInElectionIndices ?? allElectionIndices;
  const nominations: Array<NominationsFixedRow> = [];
  for (const elIdx of electionsWithNoms) {
    const electionIdSuffix = `el-${elIdx + 1}`;
    if (orgCount === 1) {
      // Single-org variant — mirrors `buildElectionConstituencyNomsSingleOrg` from perm-localisation-positive.ts; emits only the or-1 parent row + candidate child rows (no or-2 parent — that row would orphan-FK since or-2 was not seeded for this perm).
      nominations.push(
        ...buildSingleOrgNoms({
          prefix: P,
          electionIdSuffix,
          constituencyIdSuffix: 'co-1a',
          candidateIdSuffixes: candIdSuffixes,
          electionSymbolStart: (elIdx + 1) * 10
        })
      );
    } else {
      nominations.push(
        ...buildElectionConstituencyNoms({
          prefix: P,
          electionIdSuffix,
          constituencyIdSuffix: 'co-1a',
          candidateIdSuffixes: candIdSuffixes,
          electionSymbolStart: (elIdx + 1) * 10
        })
      );
    }
  }

  // --- App settings ------------------------------------------------------
  const settings = deepMerge(MINIMAL_BASE_APP_SETTINGS, settingsOverlay);

  // --- Assemble Template -------------------------------------------------
  const tpl: Template = {
    seed: 42,
    externalIdPrefix: P,
    generateTranslationsForAllLocales: false,

    elections: { count: 0, fixed: elections },
    constituency_groups: { count: 0, fixed: constituency_groups },
    constituencies: { count: 0, fixed: constituencies },
    organizations: { count: 0, fixed: orgs },
    question_categories: { count: 0, fixed: question_categories },
    questions: { count: 0, fixed: questions },
    candidates: { count: 0, fixed: candidatesArr },
    nominations: { count: 0, fixed: nominations },
    app_settings: {
      count: 0,
      fixed: [{ external_id: 'app-settings', settings }]
    }
  };

  return tpl;
}

/**
 * Single-org variant of {@link buildElectionConstituencyNoms} — emits ONLY the or-1 parent nomination + candidate child nominations (no or-2 parent row, since the single-org perm has not seeded or-2). Mirror of the file-local helper in `perm-localisation-positive.ts` — kept here so `buildMinimal({ organizations: 1 })` can produce a coherent nomination set without orphan-FK references to a missing or-2 organisation row.
 */
function buildSingleOrgNoms(opts: {
  prefix: string;
  electionIdSuffix: string;
  constituencyIdSuffix: string;
  candidateIdSuffixes: Array<string>;
  electionSymbolStart: number;
}): Array<NominationsFixedRow> {
  const { prefix: P, electionIdSuffix, constituencyIdSuffix, candidateIdSuffixes, electionSymbolStart } = opts;
  const electionExtId = `${P}${electionIdSuffix}`;
  const constituencyExtId = `${P}${constituencyIdSuffix}`;
  const key = `${electionIdSuffix}-${constituencyIdSuffix}`;
  const noms: Array<NominationsFixedRow> = [
    {
      external_id: `nom-${key}-or-1`,
      organization: { external_id: `${P}or-1` },
      election: { external_id: electionExtId },
      constituency: { external_id: constituencyExtId },
      election_round: 1
    }
  ];
  for (let i = 0; i < candidateIdSuffixes.length; i++) {
    const candIdSuffix = candidateIdSuffixes[i];
    noms.push({
      external_id: `nom-${key}-${candIdSuffix}`,
      election_symbol: String(electionSymbolStart + i),
      candidate: { external_id: `${P}${candIdSuffix}` },
      parent_nomination: { external_id: `${P}nom-${key}-or-1` },
      election: { external_id: electionExtId },
      constituency: { external_id: constituencyExtId },
      election_round: 1
    });
  }
  return noms;
}
