/* eslint-disable @typescript-eslint/no-unused-vars -- Mock stubs have intentionally unused parameters */
/**
 * Test stub for Paraglide runtime.
 * The real module is generated by the Paraglide Vite plugin at build time.
 */
export function getLocale(): string {
  return 'en';
}

export function setLocale(_locale: string): void {
  // No-op in tests
}

export const locales: Array<string> = ['en', 'fi', 'sv', 'da', 'et', 'fr', 'lb'];

export const baseLocale = 'en';

export function localizeHref(href: string, _options?: { locale?: string }): string {
  return href;
}

export function deLocalizeUrl(url: URL): URL {
  return url;
}
