/**
 * Test stub for Paraglide messages.
 * The real module is generated by the Paraglide Vite plugin at build time.
 * Returns the key as the message for any accessed key.
 */
export default new Proxy(
  {},
  {
    get: (_target, prop) => {
      if (typeof prop === 'string') {
        return (params?: Record<string, unknown>) => {
          if (params && Object.keys(params).length > 0) {
            let result = prop;
            for (const [key, value] of Object.entries(params)) {
              result = result.replace(`{${key}}`, String(value));
            }
            return result;
          }
          return prop;
        };
      }
      return undefined;
    }
  }
);
