/**
 * Defines the types of output that can be generated by the condensation process.
 */
export const ARGUMENT_TYPE = {
  LikertPros: 'likertPros',
  LikertCons: 'likertCons',
  CategoricalPros: 'categoricalPros',
  BooleanPros: 'booleanPros',
  BooleanCons: 'booleanCons'
} as const;

export type ArgumentType = (typeof ARGUMENT_TYPE)[keyof typeof ARGUMENT_TYPE];
