/**
 * The dependency-audit baseline's SHAPE, asserted rather than described.
 *
 * ## The incident this file exists for
 *
 * Locked decision D-L3(a) and roadmap criterion 4 both say the accepted baseline must be "recorded as an accepted baseline with severities", and both say it in those words. That requirement is the whole reason `npmAuditIgnoreAdvisories` in `.yarnrc.yml` was rejected as the mechanism: it is an array of bare advisory IDs carrying no severity, no date and no rationale. A JSON file can carry all three -- and can also quietly stop carrying them. `security/audit-baseline.json` is regenerated by `yarn audit:deps --update-baseline`, and a future edit to that emitter that drops the severity field would leave a file that still parses, still subtracts correctly, and no longer satisfies the criterion it was built for. A comment in the emitter would not catch that; this file does.
 *
 * ## What the marker assertion is for, and why it is the sharpest one here
 *
 * `--update-baseline` writes newly-discovered advisories with a `REVIEW REQUIRED` rationale rather than inventing a reason for accepting them. The assertion below that NO row carries that marker is what stops the affordance from being a way to clear a red: running it on a red tree moves the finding out of the audit gate and straight into this test, so the tree stays red until a human writes down why the advisory is accepted. Threat T-163-16 in the plan's register is exactly this, and this assertion is its mitigation.
 *
 * ## Why it lives in packages/dev-seed
 *
 * Same reason as its siblings `ciTypecheckGate.test.ts` and `ciSecretScanFlags.test.ts`, whose shape this file follows: `yarn test:unit` is `turbo run test:unit`, so a repo-meta spec needs a package to run in, and this package already reads repo-root files from its tests. Read `ciTypecheckGate.test.ts`'s docblock for the fuller version.
 */

import { readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';

const HERE = dirname(fileURLToPath(import.meta.url));
/** `packages/dev-seed/tests` → repo root. */
const REPO_ROOT = resolve(HERE, '../../..');

const BASELINE_PATH = resolve(REPO_ROOT, 'security/audit-baseline.json');
const YARNRC_PATH = resolve(REPO_ROOT, '.yarnrc.yml');

/** The severity vocabulary `yarn npm audit --severity` accepts, minus `info`, which cannot appear at a `high` threshold. */
const ALLOWED_SEVERITIES = ['low', 'moderate', 'high', 'critical'];

/** Kept in step with `REVIEW_MARKER` in `scripts/assert-dependency-audit.mjs`. The two must not drift: the emitter writes it, this file forbids it. */
const REVIEW_MARKER = 'REVIEW REQUIRED';

/**
 * Both settings apply to every LOCAL `yarn npm audit` as well as to CI, so either one would give a developer running the command by hand a silently filtered view of the tree. That is the reason the subtraction lives in a script instead, and it stays true only while neither key exists.
 */
const FORBIDDEN_YARNRC_KEYS = ['npmAuditIgnoreAdvisories', 'npmAuditExcludePackages'];

interface AcceptedRow {
  id: number;
  package: string;
  severity: string;
  ghsa: string;
  issue: string;
  via: string;
  rationale: string;
}

interface Baseline {
  recorded: string;
  recordedAtHead: string;
  threshold: string;
  note: string;
  accepted: Array<AcceptedRow>;
}

const baseline = JSON.parse(readFileSync(BASELINE_PATH, 'utf8')) as Baseline;
const yarnrc = readFileSync(YARNRC_PATH, 'utf8');

describe('security/audit-baseline.json carries what D-L3(a) requires of it', () => {
  it('declares the locked `high` threshold', () => {
    expect(baseline.threshold).toBe('high');
  });

  it('is not empty, so the assertions below measure something', () => {
    expect(baseline.accepted.length).toBeGreaterThan(0);
  });

  it('gives every accepted advisory a severity from the allowed set', () => {
    const bad = baseline.accepted.filter((row) => !ALLOWED_SEVERITIES.includes(row.severity));
    expect(bad.map((row) => `${row.id} (${row.package}): ${JSON.stringify(row.severity)}`)).toEqual([]);
  });

  it('records every advisory ID as a number, because the subtraction is keyed on it', () => {
    const bad = baseline.accepted.filter((row) => typeof row.id !== 'number' || !Number.isInteger(row.id));
    expect(bad.map((row) => `${row.package}: ${JSON.stringify(row.id)}`)).toEqual([]);
  });

  it('lists each advisory ID exactly once', () => {
    const seen = new Map<number, number>();
    for (const row of baseline.accepted) seen.set(row.id, (seen.get(row.id) ?? 0) + 1);
    const duplicated = [...seen.entries()].filter(([, count]) => count > 1).map(([id]) => id);
    expect(duplicated).toEqual([]);
  });

  it('gives every accepted advisory a non-empty rationale', () => {
    const bad = baseline.accepted.filter(
      (row) => typeof row.rationale !== 'string' || row.rationale.trim().length === 0
    );
    expect(bad.map((row) => `${row.id} (${row.package})`)).toEqual([]);
  });

  it(`carries no ${REVIEW_MARKER} rationale, so --update-baseline cannot be used to clear a red`, () => {
    const unreviewed = baseline.accepted.filter((row) => String(row.rationale).includes(REVIEW_MARKER));
    expect(unreviewed.map((row) => `${row.id} (${row.package})`)).toEqual([]);
  });

  it('names each accepted advisory by package and GHSA, so a row is readable without re-running the audit', () => {
    const bad = baseline.accepted.filter((row) => !row.package || !/^GHSA-/.test(String(row.ghsa)));
    expect(bad.map((row) => `${row.id}: package=${row.package} ghsa=${row.ghsa}`)).toEqual([]);
  });
});

describe('the raw `yarn npm audit` a developer runs by hand stays unfiltered', () => {
  it.each(FORBIDDEN_YARNRC_KEYS)('.yarnrc.yml declares no %s key', (key) => {
    expect(yarnrc).not.toContain(key);
  });
});
