import fs from 'fs';
import path from 'path';
import { getFlattenedTranslationKeys } from './utils/flattenKeys';
import { dirPath, locales, outputPath } from './utils/pathsAndLocales';

console.info('Generating TranslationKey type...');

// Names of translation files in the directory of the primary locale
const primaryLocale = locales.includes('en') ? 'en' : locales[0];

const primaryLocaleKeys = getTranslationKeysForLocale(primaryLocale);

const langKeys = locales.map((locale) => `lang.${locale}`);
const translationKeys = [...primaryLocaleKeys, ...langKeys].sort();

const comment = '/** Auto-generated by `/frontend/tools/translationKey/generateTranslationKeyType.ts` */';
const output = `${comment}\nexport type TranslationKey = ${translationKeys.map((s) => `'${s}'`).join(' | ')}`;

fs.writeFileSync(outputPath, output);

// Now check that the keys exists for all languages
for (const locale of locales) {
  if (locale === primaryLocale) continue;
  const localeKeys = getTranslationKeysForLocale(locale);
  const missing = primaryLocaleKeys.filter((k) => !localeKeys.includes(k));
  const extra = localeKeys.filter((k) => !primaryLocaleKeys.includes(k));
  if (missing.length + extra.length) {
    console.error(`Translation keys are missing or extra in ${locale}`);
    missing.forEach((k) => console.info(`Missing: ${k}`));
    extra.forEach((k) => console.info(`Extra:   ${k}`));
    continue;
  }
  console.info(`Translation keys are valid in ${locale}`);
}

function getTranslationKeysForLocale(locale: string): Array<string> {
  const filenames = fs.readdirSync(path.join(dirPath, primaryLocale));
  // Array of flattened translation keys
  return filenames
    .flatMap((filename) => {
      return getFlattenedTranslationKeys({ locale, dirPath, filename });
    })
    .sort();
}
