import { env } from '$env/dynamic/public';

export const constants = {
  PUBLIC_BROWSER_BACKEND_URL: env.PUBLIC_BROWSER_BACKEND_URL ?? '',
  PUBLIC_SERVER_BACKEND_URL: env.PUBLIC_SERVER_BACKEND_URL ?? '',
  PUBLIC_BROWSER_FRONTEND_URL: env.PUBLIC_BROWSER_FRONTEND_URL ?? '',
  PUBLIC_SERVER_FRONTEND_URL: env.PUBLIC_SERVER_FRONTEND_URL ?? '',
  PUBLIC_IDENTITY_PROVIDER_CLIENT_ID: env.PUBLIC_IDENTITY_PROVIDER_CLIENT_ID ?? '',
  PUBLIC_IDENTITY_PROVIDER_AUTHORIZATION_ENDPOINT: env.PUBLIC_IDENTITY_PROVIDER_AUTHORIZATION_ENDPOINT ?? '',
  PUBLIC_IDENTITY_PROVIDER_TYPE: env.PUBLIC_IDENTITY_PROVIDER_TYPE ?? 'signicat',
  PUBLIC_DEBUG: env.PUBLIC_DEBUG?.toLowerCase() === 'true',
  PUBLIC_CACHE_ENABLED: env.PUBLIC_CACHE_ENABLED?.toLowerCase() === 'true',
  PUBLIC_SUPABASE_URL: env.PUBLIC_SUPABASE_URL ?? '',
  PUBLIC_SUPABASE_ANON_KEY: env.PUBLIC_SUPABASE_ANON_KEY ?? ''
};
