import {
  PUBLIC_BROWSER_BACKEND_URL,
  PUBLIC_BROWSER_FRONTEND_URL,
  PUBLIC_SERVER_BACKEND_URL,
  PUBLIC_SERVER_FRONTEND_URL
} from '$env/static/public';

export const constants: Record<string, string> = {
  PUBLIC_BROWSER_FRONTEND_URL: PUBLIC_BROWSER_FRONTEND_URL,
  PUBLIC_SERVER_FRONTEND_URL: PUBLIC_SERVER_FRONTEND_URL,
  PUBLIC_BROWSER_BACKEND_URL: PUBLIC_BROWSER_BACKEND_URL,
  PUBLIC_SERVER_BACKEND_URL: PUBLIC_SERVER_BACKEND_URL
};
