import { env } from '$env/dynamic/public';

export const constants: Record<string, string> = {
  PUBLIC_BROWSER_BACKEND_URL: env.PUBLIC_BROWSER_BACKEND_URL,
  PUBLIC_SERVER_BACKEND_URL: env.PUBLIC_SERVER_BACKEND_URL,
  PUBLIC_IDENTITY_PROVIDER_CLIENT_ID: env.PUBLIC_IDENTITY_PROVIDER_CLIENT_ID,
  PUBLIC_IDENTITY_PROVIDER_AUTHORIZATION_ENDPOINT: env.PUBLIC_IDENTITY_PROVIDER_AUTHORIZATION_ENDPOINT,
  PUBLIC_DEBUG: env.PUBLIC_DEBUG,
  PUBLIC_FRONTEND_SENTRY_DSN: env.PUBLIC_FRONTEND_SENTRY_DSN,
  PUBLIC_FRONTEND_SENTRY_TRACES_SAMPLE_RATE: env.PUBLIC_FRONTEND_SENTRY_TRACES_SAMPLE_RATE,
  PUBLIC_FRONTEND_SENTRY_REPLAYS_SESSION_SAMPLE_RATE: env.PUBLIC_FRONTEND_SENTRY_REPLAYS_SESSION_SAMPLE_RATE,
  PUBLIC_FRONTEND_SENTRY_REPLAYS_ON_ERROR_SAMPLE_RATE: env.PUBLIC_FRONTEND_SENTRY_REPLAYS_ON_ERROR_SAMPLE_RATE
};
