import {
  PUBLIC_BACKEND_URL,
  PUBLIC_DOCKER_BACKEND_URL,
  PUBLIC_DOCKER_FRONTEND_URL,
  PUBLIC_FRONTEND_URL
} from '$env/static/public';

export const constants: Record<string, string> = {
  PUBLIC_FRONTEND_URL: PUBLIC_FRONTEND_URL,
  PUBLIC_DOCKER_FRONTEND_URL: PUBLIC_DOCKER_FRONTEND_URL,
  PUBLIC_BACKEND_URL: PUBLIC_BACKEND_URL,
  PUBLIC_DOCKER_BACKEND_URL: PUBLIC_DOCKER_BACKEND_URL
};
