/**
 * Represents a condensed argument extracted from comments.
 */
export interface Argument {
  /** The unique identifier for this argument (currently a mock id generated by the LLM) */
  id: string;
  /** The condensed argument text */
  text: string;
}
