/**
 * Defines the types of output that can be generated by the condensation process.

 * @todo
 * Implement support for the Number answer format
 */
export const CONDENSATION_TYPE = {
  LIKERT: {
    PROS: 'likertPros',
    CONS: 'likertCons'
  },
  CATEGORICAL: {
    PROS: 'categoricalPros'
    // TODO: (Optional): Add support for categorical cons
    // CONS would imply that there is a negative category, which is not the case for categorical data
    // In theory we could go through all other categories' comments and scour them for cons about this specific category
  },
  BOOLEAN: {
    PROS: 'booleanPros',
    CONS: 'booleanCons'
  }
  // TODO: Add support for NUMBER questions.
} as const;

// Flatten the hierarchy for the type union
export type CondensationOutputType =
  | typeof CONDENSATION_TYPE.LIKERT.PROS
  | typeof CONDENSATION_TYPE.LIKERT.CONS
  | typeof CONDENSATION_TYPE.CATEGORICAL.PROS
  | typeof CONDENSATION_TYPE.BOOLEAN.PROS
  | typeof CONDENSATION_TYPE.BOOLEAN.CONS;
