import { env } from '$env/dynamic/private';

export const constants: Record<string, string> = {
  BACKEND_API_TOKEN: env.BACKEND_API_TOKEN,
  IDENTITY_PROVIDER_CLIENT_SECRET: env.IDENTITY_PROVIDER_CLIENT_SECRET,
  IDENTITY_PROVIDER_ENCRYPTION_PRIVATE_KEY: env.IDENTITY_PROVIDER_ENCRYPTION_PRIVATE_KEY,
  IDENTITY_PROVIDER_JWKS_URI: env.IDENTITY_PROVIDER_JWKS_URI,
  IDENTITY_PROVIDER_TOKEN_ENDPOINT: env.IDENTITY_PROVIDER_TOKEN_ENDPOINT,
  CACHE_DIR: env.CACHE_DIR,
  CACHE_TTL: env.CACHE_TTL,
  CACHE_LRU_SIZE: env.CACHE_LRU_SIZE,
  CACHE_EXPIRATION_INTERVAL: env.CACHE_EXPIRATION_INTERVAL
};
