import { env } from '$env/dynamic/private';

export const constants = {
  BACKEND_API_TOKEN: env.BACKEND_API_TOKEN,
  IDENTITY_PROVIDER_CLIENT_SECRET: env.IDENTITY_PROVIDER_CLIENT_SECRET,
  IDENTITY_PROVIDER_DECRYPTION_JWKS: env.IDENTITY_PROVIDER_DECRYPTION_JWKS,
  IDENTITY_PROVIDER_JWKS_URI: env.IDENTITY_PROVIDER_JWKS_URI,
  IDENTITY_PROVIDER_ISSUER: env.IDENTITY_PROVIDER_ISSUER,
  IDENTITY_PROVIDER_TOKEN_ENDPOINT: env.IDENTITY_PROVIDER_TOKEN_ENDPOINT,
  LOCAL_DATA_DIR: env.LOCAL_DATA_DIR,
  CACHE_DIR: env.CACHE_DIR,
  CACHE_TTL: env.CACHE_TTL,
  CACHE_LRU_SIZE: env.CACHE_LRU_SIZE,
  CACHE_EXPIRATION_INTERVAL: env.CACHE_EXPIRATION_INTERVAL,
  LLM_OPENAI_API_KEY: env.LLM_OPENAI_API_KEY
};
