name: Playwright Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  playwright:
    name: 'Playwright Tests'
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.41.1-jammy
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: yarn install --frozen-lockfile --non-interactive
      - name: Run development server
        run: yarn dev
        background: true
      - name: Wait for server to start
        run: |
          until $(curl --output /dev/null --silent --head --fail http://localhost:5173/candidate); do
            echo 'Waiting for server to start...'
            sleep 5
          done
      - name: Run your tests
        run: npx playwright test
#        env:
#          HOME: /root
