name: QA tests & validation

on:
  push:
  pull_request:
    types:
      - opened
      - edited
      - reopened
    branches:
      - qa

jobs:
  frontend-validation:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout Frontend source code"
        uses: actions/checkout@v3

      - name: Setup Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          dir: "frontend"

      - name: "Install Frontend npm dependencies"
        uses: borales/actions-yarn@v4
        with:
          cmd: install # will run `yarn install` command
          dir: "frontend"

      - name: "Run Prettier check on frontend"
        uses: borales/actions-yarn@v4
        with:
          cmd: prettier:check
          dir: "frontend"

      - name: "Run eslint check on frontend"
        uses: borales/actions-yarn@v4
        with:
          cmd: lint
          dir: "frontend"

      - name: "Run Frontend tests"
        uses: borales/actions-yarn@v4
        with:
          cmd: test
          dir: "frontend"

  backend-validation:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend/vaa-strapi

    steps:
      - name: "Checkout Backend source code"
        uses: actions/checkout@v3

      - name: Setup Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: "Install Backend npm dependencies"
        run: |
          npm install

      - name: "Run Prettier check on Backend"
        run: |
          npm run prettier:check

#      - name: "Run Backend tests"
#        run: |
#         npm run test
