name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Version Packages
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}
    permissions:
      contents: write
      pull-requests: write
      id-token: write

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Yarn 4.13
        uses: threeal/setup-yarn-action@v2
        with:
          version: 4.13

      - name: Setup Node.js 20.18.1
        uses: actions/setup-node@v4
        with:
          node-version: 20.18.1
          cache: "yarn"
          registry-url: 'https://registry.npmjs.org'

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Create Release Pull Request or Publish
        uses: changesets/action@v1
        with:
          title: "chore: version packages"
          commit: "chore: version packages"
          publish: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
